export const breadMenu = {
    '/total/admin': [{name: '系统预览'}],
    '/user/admin': [{name: '用户管理'}],
    '/dev/admin': [{name: '设备管理'}],
    '/filter/admin': [{name: '滤芯管理'}],
    '/serve/banner': [{name: '增值服务管理'}, {name: '小程序banner'}],
    '/serve/goods': [{name: '增值服务管理'}, {name: '小程序滤芯购买'}],
    '/user/info': [{name: '用户管理'}, {name: '用户信息'}],
    '/user/mp': [{name: '用户管理'}, {name: '微信小程序'}],
    '/serve/ad': [{name: '增值服务管理'}, {name: '小程序广告'}],
    '/user/devbind': [{name: '用户管理', path: '/user'}, {name: '微信小程序', path: '/user/mp'}, {name: '设备管理'}],
    '/serve/banner/edit': [{name: '增值服务管理'}, {name: '小程序banner', path: '/serve/banner'}, {name: '小程序banner编辑'}],
    '/serve/ad/edit': [{name: '增值服务管理'}, {name: '小程序广告', path: '/serve/ad'}, {name: '小程序广告编辑'}],
    '/serve/goods/edit': [{name: '增值服务管理'}, {name: '小程序滤芯购买', path: '/serve/goods'}, {name: '小程序滤芯购买编辑'}],
    '/serve/ad-reply': [{name: '增值服务管理'}, {name: '广告应答', path: '/serve/ad-reply'}],
    '/log/loginLog': [{name: '日志管理'}, {name: '登录日志'}],
    '/log/operateLog': [{name: '日志管理'}, {name: '操作日志'}],
    '/log/errorLog': [{name: '日志管理'}, {name: '异常日志'}],
}